apiVersion: v1
kind: Service
metadata:
  name: acme-app-store-books
  labels:
    app: acme-app-store-books
spec:
 type: LoadBalancer
 ports:
 - port: 80
   targetPort: 80
 selector:
    app: acme-app-store-books