apiVersion: v1
kind: Service
metadata:
  name: acme-app-store-apps
  labels:
    app: acme-app-store-apps
spec:
 type: ClusterIP
 ports:
 - port: 80
   targetPort: 80
 selector:
    app: acme-app-store-apps